### PR TITLE
Add pydoclint entry to "Docstrings" section

### PR DESCRIPTION
**Pull request by jsh9**
Closes https://github.com/DmytroLitvinov/awesome-flake8-extensions/issues/127

### CODE REVIEW

**Comment by orsinium** [comment]
Thank you! Looks good to me. CI explodes, let me see how to fix it first. Then we can merge it :)

**Review by orsinium — APPROVED** [review]

**Comment by orsinium** [comment]
I propose not to wait for the linked issue with awesome-lint to be resolved. I'm quite sure this PR doesn't break it :)

**Review by DmytroLitvinov — APPROVED** [review]

**Comment by jsh9** [comment]
Hi @DmytroLitvinov and @orsinium , thank you both!  

Can either one of you merge this PR for me?  It doesn't seem that I have the proper permission to do so:

image

**Comment by orsinium** [comment]
Of course, you don't. Only maintainers can merge things.

Merged. Thank you for your patience. Feel free to bring more projects when you have something new ;)

**Pull request merged**
