### PR TITLE
typo: PEP406 => PEP604

### PR DESCRIPTION
**Pull request by vpoulailleau**
And also add a link to the PEP.

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hi @vpoulailleau ,
Thanks for checking it.
Can you take a look at failed CI and fix issue?

**Comment by vpoulailleau** [comment]
@DmytroLitvinov Two plugins manage PEP 604, as I added a link to the PEP, the CI tells that there are two links to the same document… Should I remove the second link (that appears after the link I added)?

**Comment by DmytroLitvinov** [comment]
I would leave 2 links.
I am not sure, maybe `<!--lint ignore double-link -->` will help. Found it [here](https://github.com/sindresorhus/awesome-lint/issues/145)

**Comment by languitar** [comment]
https://commonmark.org/help/tutorial/07-links.html

You should probably use the syntax where links are paced at the bottom of the document and only referenced inline to avoid this.

**Pull request merged**
