### PR TITLE
Add flake8-clean-block and flake8-indent-in-def

### PR DESCRIPTION
**Pull request by cyyc1**
Adding two plugins that I wrote myself. I've covered them with extensive test cases and I plan to maintain them.

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Hi @cyyc1 , 
Thanks for creating new plugins. 
Let's keep that PR for some period of time because we want to list plugins here that are mature.

**Comment by cyyc1** [comment]
> Hi @cyyc1 , Thanks for creating new plugins. Let's keep that PR for some period of time because we want to list plugins here that are mature.

Thanks for the response. Would you have a written criterion as to what qualifies as "mature"? Is it time since creation, or number of stars?

**Comment by DmytroLitvinov** [comment]
I don't have clean points what is "mature". But you are right that it is based on stars and time since creation. I would not close that PR and just give it time.

**Comment by cyyc1** [comment]
Yes this makes sense. Let's give it a few months then

**Review by orsinium — APPROVED** [review]

**Review by DmytroLitvinov — APPROVED** [review]

**Comment by cleder** [comment]
@cyyc1 can you resolve the merge conflicts please?

**Comment by orsinium** [comment]
Thank you for your contribution and patience. I hope you had fun making the plugins :)

**Comment by cyyc1** [comment]
Thank you very much @orsinium for resolving merge conflicts and merging it for me!

**Pull request merged**
